FROM node:18-alpine AS Builder

WORKDIR app

COPY package-lock.json package.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:alpine

COPY --from=Builder app/build /usr/share/nginx/html

EXPOSE 80

CMD [ "nginx","-g","daemon off;" ]